# Generated by Django 6.0.7 on 2026-07-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
