# Generated by Django 6.0.7 on 2026-07-23 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 23, 3, 45, 32, 810983)),
        ),
    ]
