# Generated by Django 6.0.7 on 2026-07-26 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_author_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 26, 17, 13, 38, 172960)),
        ),
    ]
