# Generated by Django 6.0.7 on 2026-07-27 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 27, 0, 51, 31, 124154)),
        ),
    ]
