# Generated by Django 6.0.7 on 2026-07-31 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_published_alter_rating_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 7, 31, 23, 52, 44, 265947)),
        ),
    ]
