# Generated by Django 6.0.7 on 2026-08-01 19:26

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_post_ratings_alter_post_published_alter_rating_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='instructions',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 1, 19, 26, 36, 760707)),
        ),
        migrations.AlterField(
            model_name='post',
            name='ratings',
            field=models.ManyToManyField(through='posts.Rating', through_fields=('post', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
