# Generated by Django 6.0.7 on 2026-08-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_rename_description_post_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default='8/1/2026'),
        ),
    ]
