# Generated by Django 6.0.7 on 2026-08-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_post_ingredients_alter_post_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default='8/1/2026'),
        ),
    ]
