# Generated by Django 6.0.7 on 2026-08-12 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_post_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='carbs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='fats',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='proteins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default='8/12/2026'),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('protiens', models.IntegerField()),
                ('carbs', models.IntegerField()),
                ('fats', models.IntegerField()),
                ('calories', models.IntegerField()),
                ('base_serving', models.IntegerField()),
                ('base_unit', models.CharField()),
                ('ingredient_list', models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='posts.ingredientlist')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='ingredient_list',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='posts', to='posts.ingredientlist'),
        ),
    ]
