# Generated by Django 6.0.7 on 2026-08-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_ingredientlist_remove_post_ingredients_post_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default='8/14/2026'),
        ),
    ]
