# Generated by Django 6.0.7 on 2026-08-11 00:43

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_post_ingredients_post_calories_post_carbs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateField(default='8/11/2026'),
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.OneToOneField(default=posts.models.get_default_post, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='posts.post')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='posts.ingredient'),
        ),
    ]
