# Generated by Django 6.0.7 on 2026-08-11 00:57

import django.db.models.deletion
import posts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_remove_food_post_alter_post_published_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='list',
            field=models.ForeignKey(default=posts.models.get_default_ingredient, on_delete=django.db.models.deletion.RESTRICT, related_name='foods', to='posts.ingredient'),
        ),
    ]
