# Generated by Django 6.0.7 on 2026-09-24 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_instructions_alter_recipe_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
