# Generated by Django 6.0.7 on 2026-09-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='serves',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
